"""
测试完整工作流程：
1. 自动分类 → 生成Web页面（无需审核）
2. 人工审核 → 重新生成Web页面（使用审核结果）
"""

print("="*80)
print("🧪 工作流程测试：Web页面生成")
print("="*80)

print("\n场景说明:")
print("="*80)

print("\n【场景1】首次运行（无人工审核）")
print("-" * 80)
print("流程:")
print("  1. 数据采集")
print("  2. 自动分类（AI分类器）")
print("  3. 智能分析")
print("  4. 数据可视化")
print("  5. 生成Web页面 ✓")
print("")
print("结果:")
print("  ✓ 使用自动分类结果生成Web页面")
print("  ✓ 页面包含所有内容（包括低置信度的）")
print("  ✓ 文件名: web_output/index.html")
print("  ✓ 数据文件: ai_tracker_data_YYYYMMDD_HHMMSS.json")

print("\n【场景2】人工审核后（有修正）")
print("-" * 80)
print("流程:")
print("  1. 加载已有数据")
print("  2. 选择菜单: 5. 人工审核")
print("  3. 修正错误分类（如: product → market）")
print("  4. 保存审核结果")
print("  5. 询问: 是否重新生成Web页面? Y")
print("  6. 重新分析 → 重新生成图表 → 重新生成Web页面 ✓")
print("")
print("结果:")
print("  ✓ 使用审核后的结果重新生成Web页面")
print("  ✓ 页面反映人工修正的分类")
print("  ✓ 删除的垃圾内容不会出现")
print("  ✓ 文件名: web_output/index.html (覆盖)")
print("  ✓ 数据文件: ai_tracker_data_reviewed_YYYYMMDD_HHMMSS.json")

print("\n【对比】审核前后的差异")
print("-" * 80)
print("")
print("审核前 Web页面:")
print("  - 总内容: 100条")
print("  - 产品类: 30条（包含5条误判的融资新闻）")
print("  - 市场类: 20条")
print("  - 垃圾内容: 2条（显示在页面中）")
print("")
print("审核后 Web页面:")
print("  - 总内容: 98条（删除2条垃圾）")
print("  - 产品类: 25条（修正后）")
print("  - 市场类: 25条（+5条从产品类修正过来）")
print("  - 垃圾内容: 0条（已删除）")

print("\n【技术实现】")
print("-" * 80)
print("")
print("1. 初始生成（run_full_pipeline）:")
print("   ```python")
print("   self.data = self.classifier.classify_batch(all_items)")
print("   self.trends = self.analyzer.analyze_trends(self.data)")
print("   self.chart_files = self.visualizer.visualize_all(self.trends)")
print("   web_file = self.web_publisher.generate_html_page(")
print("       self.data, self.trends, self.chart_files")
print("   )")
print("   ```")
print("")
print("2. 人工审核修改数据:")
print("   ```python")
print("   # 修改分类")
print("   item['content_type'] = 'market'  # product → market")
print("   item['confidence'] = 1.0")
print("   item['manually_reviewed'] = True")
print("   ")
print("   # 删除垃圾")
print("   item['is_spam'] = True")
print("   self.data = [item for item in self.data if not item.get('is_spam')]")
print("   ```")
print("")
print("3. 重新生成（_regenerate_after_review）:")
print("   ```python")
print("   # 使用审核后的 self.data")
print("   self.trends = self.analyzer.analyze_trends(self.data)")
print("   self.chart_files = self.visualizer.visualize_all(self.trends)")
print("   web_file = self.web_publisher.generate_html_page(")
print("       self.data, self.trends, self.chart_files")
print("   )")
print("   # 保存为 ai_tracker_data_reviewed_*.json")
print("   ```")

print("\n【数据流示意图】")
print("-" * 80)
print("")
print("无审核流程:")
print("  采集 → 分类 → 分析 → 可视化 → Web页面")
print("   ↓      ↓      ↓       ↓         ↓")
print("  100条  100条  trends  charts   index.html")
print("")
print("有审核流程:")
print("  采集 → 分类 → 【人工审核】→ 重新分析 → 重新可视化 → 新Web页面")
print("   ↓      ↓         ↓            ↓           ↓           ↓")
print("  100条  100条    98条修正     new trends  new charts  index.html")
print("                  (删除2条)")

print("\n【关键代码位置】")
print("-" * 80)
print("")
print("1. TheWorldOfAI.py:")
print("   - run_full_pipeline(): 初始流程（包含Web生成）")
print("   - _manual_review(): 人工审核")
print("   - _regenerate_after_review(): 审核后重新生成 ← 新增")
print("")
print("2. manual_reviewer.py:")
print("   - batch_review(): 批量审核，修改self.data")
print("")
print("3. web_publisher.py:")
print("   - generate_html_page(data, trends, charts): 生成页面")
print("   - 接收的data参数会反映审核后的结果")

print("\n【使用示例】")
print("-" * 80)
print("")
print("# 第一次运行")
print("$ python TheWorldOfAI.py")
print("选择: 1. 一键更新数据与报告")
print("→ 生成 web_output/index.html（使用自动分类）")
print("")
print("# 查看发现有错误，进行审核")
print("选择: 5. 人工审核分类")
print("→ 修正 5 条错误")
print("→ 删除 2 条垃圾")
print("→ 询问: 是否重新生成Web页面? Y")
print("→ 重新生成 web_output/index.html（使用审核结果）")
print("")
print("# 查看学习反馈")
print("选择: 6. 学习反馈分析")
print("→ 分析审核模式")
print("→ 生成改进建议")

print("\n【验证方法】")
print("-" * 80)
print("")
print("1. 运行初始流程:")
print("   python TheWorldOfAI.py → 选择1")
print("   检查: web_output/index.html 是否生成")
print("")
print("2. 进行人工审核:")
print("   python TheWorldOfAI.py → 选择5")
print("   修正几条内容，选择重新生成")
print("   检查: web_output/index.html 是否更新")
print("")
print("3. 对比内容:")
print("   审核前后的统计数据应该不同")
print("   删除的内容不应该出现在页面中")

print("\n" + "="*80)
print("✅ 工作流程设计完成！")
print("="*80)

print("\n总结:")
print("  1. ✓ 无审核时：自动生成Web页面")
print("  2. ✓ 有审核时：使用审核结果重新生成")
print("  3. ✓ 数据一致性：Web页面始终反映当前数据状态")
print("  4. ✓ 用户友好：审核后自动询问是否重新生成")
